<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\controller;

use app\common\model\system\Admin;

/**
 * 系统中台控制器基类
 *
 * @author 牧羊人
 * @since 2020-04-21
 */
class Backend extends CommonBase
{
//    // 模型
//    protected $model;
//    // 服务
//    protected $service;
//    // 校验
//    protected $validate;
//    // 网络请求
//    protected $param;
//
//    /**
//     * 初始化
//     */
//    public function initialize()
//    {
//        parent::initialize(); // TODO: Change the autogenerated stub
//
//        // 初始化网络请求
//        $this->initRequestInfo();
//    }
//
//    /**
//     * 初始化请求信息
//     */
//    public function initRequestInfo()
//    {
//        // 解析请求参数
//        $this->param = $this->request->param();
//        // 操作方法名(登录、注册时不需要验证)
//        $action = request()->action();
//        // 无需校验的方法名
//        $noNeedAction = ["login"];
//        // 方法校验
//        if (!in_array($action, $noNeedAction)) {
//            // Token令牌(校验)
//            $token = request()->header("token");
//            if (!$token) {
//                $this->jsonReturn("token令牌不能为空", false, null, -2);
//            }
//            // 解析Jwt
//            $jwt = new \Jwt();
//            $uid = $jwt->verifyToken($token);
//            if (!$uid) {
//                $this->jsonReturn("token解析失败", false, null, -2);
//            }
//            $admin_model = new Admin();
//            $admin_info = $admin_model->getInfo($uid);
//            if (!$admin_info) {
//                $this->jsonReturn("用户不存在");
//            }
//        }
//    }


}