
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\admin\service\<?php echo $moduleName?>Service;
use app\common\controller\Backend;

/**
 * <?php echo $moduleTitle?>管理-控制器
 * @author <?php echo $author?>

 * @since: <?php echo $since?>

 * Class <?php echo $moduleName?>

 * @package app\admin\controller
 */
class <?php echo $moduleName?> extends Backend
{
    /**
     * 初始化方法
     * @author <?php echo $author?>

     * @since: <?php echo $since?>

     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\<?php echo $moduleName?>();
        $this->service = new <?php echo $moduleName?>Service();
    }
}