
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\service;


use app\admin\model\<?php echo $moduleName?>;
use app\common\service\BaseService;

/**
 * <?php echo $moduleTitle?>管理-服务类
 * @author <?php echo $author?>

 * @since: <?php echo $since?>

 * Class <?php echo $moduleName?>Service
 * @package app\admin\service
 */
class <?php echo $moduleName?>Service extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new <?php echo $moduleName?>();
    }

<?php if ($moduleImage) {?>
	/**
     * 添加或编辑
     * @return array
     * @since 2020/7/15
     * @author 牧羊人
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
	<?php foreach ($columnList as $val) { ?>
        <?php if (isset($val['columnImage']) && $val['columnImage']) {?>

		// <?php $val['columnComment']?>处理
        $<?php echo $val['columnName']?> = trim($data['<?php echo $val['columnName']?>']);
        if (strpos($<?php echo $val['columnName']?>, "temp")) {
            $data['<?php echo $val['columnName']?>'] = save_image($<?php echo $val['columnName']?>, '<?php echo strtolower($moduleName)?>');
        } else {
            $data['<?php echo $val['columnName']?>'] = str_replace(IMG_URL, "", $data['<?php echo $val['columnName']?>']);
        }
        <?php } ?>
    <?php } ?>
        
        return parent::edit($data); // TODO: Change the autogenerated stub
    }
<?php } ?>

}