<?php


namespace app\admin\model;


use app\common\model\BaseModel;

/**
 * 广告位-模型
 * @author 牧羊人
 * @since 2020/7/2
 * Class AdSort
 * @package app\admin\model
 */
class AdSort extends BaseModel
{
    // 设置数据表名
    protected $name = "ad_sort";


    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 获取站点
            if ($info['item_id']) {
                $item_model = new Item();
                $item_info = $item_model->getInfo($info['item_id']);
                $info['item_name'] = $item_info['name'];
            }

            // 获取栏目
            if ($info['cate_id']) {
                $item_cate_model = new ItemCate();
                $cate_name = $item_cate_model->getCateName($info['cate_id'], ">>");
                $info['cate_name'] = $cate_name;
            }

            // 使用平台
            if ($info['platform']) {
                $info['platform_name'] = config('admin.ad_platform')[$info['platform']];
            }
        }
        return $info;
    }
}