<?php


namespace app\admin\controller;


use app\admin\service\ConfigGroupService;
use app\common\controller\Backend;

/**
 * 配置分组-控制器
 * @author 牧羊人
 * @since 2020/7/1
 * Class Configgroup
 * @package app\admin\controller
 */
class Configgroup extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/1
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\ConfigGroup();
        $this->service = new ConfigGroupService();
    }
}