<?php


namespace app\admin\controller;


use app\admin\service\DepService;
use app\common\controller\Backend;

/**
 * 部门-控制器
 * @author 牧羊人
 * @since 2020/7/2
 * Class Dep
 * @package app\admin\controller
 */
class Dep extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/2
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Dep();
        $this->service = new DepService();
    }
}