<?php


namespace app\admin\controller;


use app\admin\service\DicTypeService;
use app\common\controller\Backend;

/**
 * 字典类型-控制器
 * @author 牧羊人
 * @since 2020/7/2
 * Class Dictype
 * @package app\admin\controller
 */
class Dictype extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/2
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\DicType();
        $this->service = new DicTypeService();
    }
}