<?php


namespace app\admin\controller;


use app\admin\service\MenuService;
use app\common\controller\Backend;
use \think\facade\View;

/**
 * 后台主页控制器
 * @author 牧羊人
 * @since: 2020/6/30
 * Class Index
 * @package app\admin\controller
 */
class Index extends Backend
{
    /**
     * 初始化方法
     * @author 牧羊人
     * @since: 2020/6/30
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 后台主入口
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since: 2020/6/30
     * @author 牧羊人
     */
    public function index()
    {
        // 取消模板布局
        $this->app->view->layout(false);

        // 获取导航菜单
        $menuService = new MenuService();
        $result = $menuService->getNavbarMenu($this->permission);
        View::assign("menuList", $result['data']);
        return $this->render();
    }

    /**
     * 欢迎页
     * @author 牧羊人
     * @since: 2020/6/30
     */
    public function main()
    {
        // 取消模板布局
        $this->app->view->layout(false);
        return $this->render();
    }

}