<?php


namespace app\admin\controller;


use app\admin\service\PositionService;
use app\common\controller\Backend;

/**
 * 岗位管理-控制器
 * @author 牧羊人
 * @since 2020/7/1
 * Class Position
 * @package app\admin\controller
 */
class Position extends Backend
{
    /**
     * 初始化方法
     * @author 牧羊人
     * @since 2020/7/1
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Position();
        $this->service = new PositionService();
    }
}