<?php


namespace app\admin\controller;


use app\admin\service\UserLevelService;
use app\common\controller\Backend;

/**
 * 会员等级-控制器
 * @author 牧羊人
 * @since 2020/7/3
 * Class Userlevel
 * @package app\admin\controller
 */
class UserLevel extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/3
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\UserLevel();
        $this->service = new UserLevelService();
    }
}